using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Linq;
using SharPipes.Pipes.Base.Events;

namespace SharPipes.Pipes.Base
{
    public class PipeLine
    {
        public event EventHandler<ElementAddedEventArgs> ElementAdded;
        public event EventHandler<ElementRemovedEventArgs> ElementRemoved;
        public event EventHandler<ElementsLinkedEventArgs> ElementsLinked;
        public event EventHandler<ElementsUnlinkedEventArgs> ElementsUnlinked;

        private void OnElementAdded(IPipeElement element)
        {
            ElementAdded?.Invoke(this, new ElementAddedEventArgs(element));
        }

        private void OnElementRemoved(IPipeElement element)
        {
            ElementRemoved?.Invoke(this, new ElementRemovedEventArgs(element));
        }

        private void OnElementsLinked(IPipeSrcPad src, IPipeSinkPad sink)
        {
            ElementsLinked?.Invoke(this, new ElementsLinkedEventArgs(src, sink));
        }

        private void OnElementsUnlinked(IPipeSrcPad src, IPipeSinkPad sink)
        {
            ElementsUnlinked?.Invoke(this, new ElementsUnlinkedEventArgs(src, sink));
        }

        private readonly IList<IPipeElement> elements = new List<IPipeElement>();
        private readonly IList<IPipeEdge> links = new List<IPipeEdge>();

        public void Add(IPipeElement element)
        {
            elements.Add(element);
            this.OnElementAdded(element);
        }

        public IPipeElement CreateNodeFromTemplate(IPipeElement template)
        {
            IPipeElement node = (IPipeElement)template.GetType().GetConstructor(new Type[] { }).Invoke(new object[] { });
            return node;
        }

        private (GraphState, List<IPipeElement>?) GetOrderedElements()
        {
            List<IPipeElement>? orderedList = new List<IPipeElement>();
            // TODO Refactor to use an autogenerated node name instead of the nodes hash
            Dictionary<IPipeElement, IList<IPipeElement>> prevNodeList = new Dictionary<IPipeElement, IList<IPipeElement>>();
            Dictionary<IPipeElement, IList<IPipeElement>> nextNodeList = new Dictionary<IPipeElement, IList<IPipeElement>>();
            IList<IPipeElement> startNodes = new List<IPipeElement>();

            foreach (var node in elements)
            {
                var state = node.Check();
                if (state != GraphState.OK)
                {
                    return (state, null);
                }

                var prevNodes = node.GetPrevNodes();

                bool nodeAdded = false;

                foreach (var prev in prevNodes)
                {
                    if (!prevNodeList.ContainsKey(prev))
                    {
                        prevNodeList.Add(prev, new List<IPipeElement>());
                    }
                    if (!nextNodeList.ContainsKey(node))
                    {
                        nextNodeList.Add(node, new List<IPipeElement>());
                    }

                    prevNodeList[prev].Add(node);
                    nextNodeList[node].Add(prev);
                    nodeAdded = true;
                }

                if (!nodeAdded) {

                    startNodes.Add(node);
                }
            }

            while (startNodes.Count > 0)
            {
                var node = startNodes[0];
                startNodes.RemoveAt(0);

                orderedList.Add(node);

                if (prevNodeList.ContainsKey(node))
                {
                    while (prevNodeList[node].Count > 0)
                    {
                        var prevNode = prevNodeList[node][0];
                        prevNodeList[node].Remove(prevNode);
                        nextNodeList[prevNode].Remove(node);

                        if (nextNodeList[prevNode].Count == 0)
                        {
                            nextNodeList.Remove(prevNode);
                            startNodes.Add(prevNode);
                        }
                    }
                    prevNodeList.Remove(node);
                }
            }

            if (prevNodeList.Count > 0 || nextNodeList.Count > 0 || startNodes.Count > 0)
            {
                return (GraphState.CYCLE, null);
            }

            return (GraphState.OK, orderedList);
        }

        private void Unlink(IPipeSrcPad srcPad)
        {
            var peer = srcPad.Peer;
            if (peer != null)
            {
                srcPad.Unlink();
                this.OnElementsUnlinked(srcPad, peer);
            }
        }

        private void Unlink(IPipeSinkPad sinkPad)
        {
            var peer = sinkPad.Peer;
            if (peer != null)
            {
                sinkPad.Unlink();
                this.OnElementsUnlinked(peer, sinkPad);
            }
        }

        public void Remove(IPipeElement element)
        {
            foreach( var sink in element.GetSinkPads())
            {
                Unlink(sink);
            }

            foreach (var src in element.GetSrcPads())
            {
                Unlink(src);
            }

            this.elements.Remove(element);
            this.OnElementRemoved(element);
        }

        public void Connect<TValue>(PipeSrcPad<TValue> From, PipeSinkPad<TValue> To)
        {
            PipeEdge<TValue> e = new PipeEdge<TValue>(From, To);
            From.Edge = e;
            To.Edge = e;
            this.links.Add(e);
            this.OnElementsLinked(From, To);
        }

        public async Task Start()
        {
            var (state, orderedElements) = GetOrderedElements();
            if(state == GraphState.OK && orderedElements!= null)
            {
                orderedElements.Reverse();

                foreach (var elem in orderedElements)
                {
                    await elem.Start();
                }
            }
        }

        static Type? IsInstanceOfGenericType(Type genericType, Type instanceType)
        {
            while (instanceType != null)
            {
                if (instanceType.IsGenericType &&
                    instanceType.GetGenericTypeDefinition() == genericType)
                {
                    return instanceType;
                }
                instanceType = instanceType.BaseType;
            }
            return null;
        }

        public bool TryConnect(IPipeSrcPad src, IPipeSinkPad sink)
        {
            var srcType = src.GetType();
            var sinkType = sink.GetType();

            var srcBaseType = IsInstanceOfGenericType(typeof(PipeSrcPad<>), srcType);
            var sinkBaseType = IsInstanceOfGenericType(typeof(PipeSinkPad<>), sinkType);

            if (srcBaseType == null)
            {
                return false;
            } 
            if(sinkBaseType == null)
            {
                return false;
            }
            if(!srcBaseType.GenericTypeArguments.SequenceEqual(sinkBaseType.GenericTypeArguments))
            {
                return false;
            }

            MethodInfo? genericConnect = typeof(PipeLine).GetMethod(nameof(Connect));
            if (genericConnect == null)
            {
                return false;
            }

            var specificConnect = genericConnect.MakeGenericMethod(srcBaseType.GenericTypeArguments);
                        
            Unlink(sink);
            Unlink(src);
            specificConnect.Invoke(this, new object[] { src, sink });

            return true;
        }




        public async Task Stop()
        {
            var (state, orderedElements) = GetOrderedElements();
            if (state == GraphState.OK && orderedElements != null)
            {
                foreach (var elem in orderedElements)
                {
                    await elem.Stop();
                }
            }
        }
    }
}
