using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Linq;
using SharPipes.Pipes.Base.PipeLineDefinitions;

namespace SharPipes.Pipes.Base
{
    public class PipeLine
    {
        private readonly IList<IPipeElement> elements = new List<IPipeElement>();
        private readonly IList<IPipeEdge> links = new List<IPipeEdge>();

        public PipeLineDefinition GetDefinition()
        {
            var pipeline = new PipeLineDefinition();

            foreach( var element in this.elements)
            {
                pipeline.Elements.Add(new ElementDefinition(PipeElementFactory.GetName(element.GetType()), element.Name, element.GetPropertyValues().ToList()));
            }

            foreach (var link in this.links)
            {
                pipeline.Links.Add(new LinkDefinition(link.From.Parent.Name, link.From.Name, link.To.Parent.Name, link.To.Name ));
            }

            return pipeline;
        }

        public IList<string> FromDefinition(PipeLineDefinition definition)
        {
            IList<string> errors = new List<string>();
            this.elements.Clear();
            this.links.Clear();

            Dictionary<string, IPipeElement> elementCache = new Dictionary<string, IPipeElement>();

            foreach(var element in definition.Elements)
            {
                IPipeElement? pipeElement = PipeElementFactory.Make(element.TypeFactory, element.Name);
                if (pipeElement != null)
                {
                    this.elements.Add(pipeElement);
                    
                    foreach(var propvalue in element.Properties)
                    {
                        if(!pipeElement.SetPropertyValue(propvalue))
                        {
                            errors.Add($"Property {propvalue} could not be set.");
                        }
                    }

                    elementCache.Add(element.Name, pipeElement);
                }
            }

            foreach(var link in definition.Links)
            {
                IPipeElement? fromElement = elementCache[link.FromElement];
                IPipeElement? toElement = elementCache[link.ToElement];

                if(fromElement == null)
                {
                    errors.Add($"Could not Link from {link.FromElement}:{link.FromPad} because the Element doesn't exist");
                    continue;
                }
                if (fromElement == null)
                {
                    errors.Add($"Could not Link to {link.ToElement}:{link.ToPad} because the Element doesn't exist");
                    continue;
                }

                IPipeSrcPad? srcPad = fromElement.GetSrcPad(link.FromPad);
                IPipeSinkPad? sinkPad = toElement.GetSinkPad(link.ToPad);

                if (srcPad == null)
                {
                    errors.Add($"Could not Link from {link.FromElement}:{link.FromPad} because the Pad doesn't exist");
                    continue;
                }
                if (sinkPad == null)
                {
                    errors.Add($"Could not Link to {link.ToElement}:{link.ToPad} because the Pad doesn't exist");
                    continue;
                }

                if(!this.TryConnect(srcPad, sinkPad))
                {
                    errors.Add($"Could not Link to {link.ToElement}:{link.ToPad} because the types don't match");
                    continue;
                }

            }

            return errors;
        }

        public void Add(IPipeElement node)
        {
            elements.Add(node);
        }

        public IPipeElement CreateNodeFromTemplate(IPipeElement template)
        {
            IPipeElement node = (IPipeElement)template.GetType().GetConstructor(new Type[] { }).Invoke(new object[] { });
            this.Add(node);
            return node;
        }

        private (GraphState, List<IPipeElement>?) GetOrderedElements()
        {
            List<IPipeElement>? orderedList = new List<IPipeElement>();
            // TODO Refactor to use an autogenerated node name instead of the nodes hash
            Dictionary<IPipeElement, IList<IPipeElement>> prevNodeList = new Dictionary<IPipeElement, IList<IPipeElement>>();
            Dictionary<IPipeElement, IList<IPipeElement>> nextNodeList = new Dictionary<IPipeElement, IList<IPipeElement>>();
            IList<IPipeElement> startNodes = new List<IPipeElement>();

            foreach (var node in elements)
            {
                var state = node.Check();
                if (state != GraphState.OK)
                {
                    return (state, null);
                }

                var prevNodes = node.GetPrevNodes();

                bool nodeAdded = false;

                foreach (var prev in prevNodes)
                {
                    if (!prevNodeList.ContainsKey(prev))
                    {
                        prevNodeList.Add(prev, new List<IPipeElement>());
                    }
                    if (!nextNodeList.ContainsKey(node))
                    {
                        nextNodeList.Add(node, new List<IPipeElement>());
                    }

                    prevNodeList[prev].Add(node);
                    nextNodeList[node].Add(prev);
                    nodeAdded = true;
                }

                if(!nodeAdded){
                    
                    startNodes.Add(node);
                }
            }

            while(startNodes.Count > 0)
            {
                var node = startNodes[0];
                startNodes.RemoveAt(0);

                orderedList.Add(node);

                if (prevNodeList.ContainsKey(node))
                {
                    while ( prevNodeList[node].Count > 0)
                    {
                        var prevNode = prevNodeList[node][0];
                        prevNodeList[node].Remove(prevNode);
                        nextNodeList[prevNode].Remove(node);

                        if(nextNodeList[prevNode].Count == 0)
                        {
                            nextNodeList.Remove(prevNode);
                            startNodes.Add(prevNode);
                        }
                    }
                    prevNodeList.Remove(node);
                }
            }

            if(prevNodeList.Count > 0 || nextNodeList.Count > 0 || startNodes.Count > 0)
            {
                return (GraphState.CYCLE, null);
            }

            return (GraphState.OK, orderedList);
        }

        public void Remove(IPipeElement element)
        {
            foreach( var sink in element.GetSinkPads())
            {
                sink.Unlink();
            }

            foreach (var src in element.GetSrcPads())
            {
                src.Unlink();
            }

            this.elements.Remove(element);
        }

        public void Connect<TValue>(PipeSrcPad<TValue> From, PipeSinkPad<TValue> To)
        {
            PipeEdge<TValue> e = new PipeEdge<TValue>(From, To);
            From.Edge = e;
            To.Edge = e;
            this.links.Add(e);
        }

        public async Task Start()
        {
            var (state, orderedElements) = GetOrderedElements();
            if(state == GraphState.OK && orderedElements!= null)
            {
                orderedElements.Reverse();

                foreach (var elem in orderedElements)
                {
                    await elem.Start();
                }
            }
        }

        static Type? IsInstanceOfGenericType(Type genericType, Type instanceType)
        {
            while (instanceType != null)
            {
                if (instanceType.IsGenericType &&
                    instanceType.GetGenericTypeDefinition() == genericType)
                {
                    return instanceType;
                }
                instanceType = instanceType.BaseType;
            }
            return null;
        }

        public bool TryConnect(IPipeSrcPad src, IPipeSinkPad sink)
        {
            var srcType = src.GetType();
            var sinkType = sink.GetType();

            var srcBaseType = IsInstanceOfGenericType(typeof(PipeSrcPad<>), srcType);
            var sinkBaseType = IsInstanceOfGenericType(typeof(PipeSinkPad<>), sinkType);

            if (srcBaseType == null)
            {
                return false;
            } 
            if(sinkBaseType == null)
            {
                return false;
            }
            if(!srcBaseType.GenericTypeArguments.SequenceEqual(sinkBaseType.GenericTypeArguments))
            {
                return false;
            }

            MethodInfo? genericConnect = typeof(PipeLine).GetMethod(nameof(Connect));
            if (genericConnect == null)
            {
                return false;
            }

            var specificConnect = genericConnect.MakeGenericMethod(srcBaseType.GenericTypeArguments);
                        
            sink.Unlink();
            src.Unlink();
            specificConnect.Invoke(this, new object[] { src, sink });

            return true;
        }




        public async Task Stop()
        {
            var (state, orderedElements) = GetOrderedElements();
            if (state == GraphState.OK && orderedElements != null)
            {
                foreach (var elem in orderedElements)
                {
                    await elem.Stop();
                }
            }
        }
    }
}
