image: mcr.microsoft.com/dotnet/core/sdk:3.0

build_job:
  stage: build
  only: 
   - tags
   - web
  script:
   - dotnet build -o /bin
  artifacts:
    expire_in: 1 week
    paths:
      - /bin
   
deploy_job:
  stage: deploy
  script:
   - dotnet publish -c Release -r win7-x64 --self-contained -o /published
  only:
    - tags
  dependencies:
    - build_job
  artifacts:
    paths:
      - /published