# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: alpine

stages:
 - build
 - test
 - document
 - deploy

pages:
  stage: document
  script:
    - apk update && apk add doxygen
    - doxygen doxygen/Doxyfile
    - ls
    - ls doxygen
    - ls doxygen/documentation
    - ls doxygen/documentation/html
    - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
      - public
  only:
   - master
