image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
 - build
 - test
 - document
 - deploy

docfx:
  stage: document
  before_script:
    - dotnet add package docfx.console --version 2.43.2
  script:
    - ls docfx.console/tools/
  artifacts:
    paths:
      - public
  only:
    - master